
services:
  redis:
    build: .
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["sh", "-c", "exec redis-server /usr/local/etc/redis/redis.conf --requirepass $$REDIS_PASSWORD"]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  node-app:
    image: node:18-alpine
    working_dir: /usr/src/app
    volumes:
      - ./apps/node:/usr/src/app
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["sh", "-c", "npm install && node index.js"]
    #profiles: ["node"]

  python-app:
    image: python:3.11-slim
    working_dir: /usr/src/app
    volumes:
      - ./apps/python:/usr/src/app
    depends_on:
      - redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["sh", "-c", "pip install redis && python app.py"]
    #profiles: ["python"]
