version: '3.8'

services:
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        environment:
            #- MYSQL_DATABASE=testdb
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - '3306:3306'
        volumes:
            - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
